name: Pull Request checks

on:
  workflow_call:

jobs:
  phpmd:
    runs-on: ubuntu-latest
    name: phpmd
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files from caller repository
        id: changedFiles
        uses: tj-actions/changed-files@v31
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}

      # Needed to have access to the linter files
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          repository: pmagentur/linting-php
          path: linting-php

      - name: Linting
        id: linter
        uses: pmagentur/linting-action@v0.2
        with:
          changed-files: ${{ steps.changedFiles.outputs.all_changed_files }}
          linter-command: "php linting-php/phpmd/phpmd.phar {files} checkstyle linting-php/phpmd/config.xml"
          relevant-file-endings: '["php"]'
          parser-type: 'xml'
          annotation-parser: 'linting-php/phpmd/annotationParser.js'

      - name: Add Annotations
        uses: pmagentur/linting-annotations@v0.1
        if: failure() && steps.linter.outputs.annotations != ''
        with:
          commitSha: ${{ github.event.pull_request.head.sha }}
          checkName: 'PHP Linting'
          annotations: ${{ steps.linter.outputs.annotations }}

  phpdoctor:
    runs-on: ubuntu-latest
    name: phpdoctor
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files from caller repository
        id: changedFiles
        uses: tj-actions/changed-files@v31
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}

      # Needed to have access to the linter files
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          repository: pmagentur/linting-php
          path: linting-php

      - name: Linting
        id: linter
        uses: pmagentur/linting-action@v0.2
        with:
          changed-files: ${{ steps.changedFiles.outputs.all_changed_files }}
          linter-command: "php linting-php/phpdoctor/phpdoctor.phar analyse {files}"
          relevant-file-endings: '["php"]'
          parser-type: 'custom'
          annotation-parser: 'linting-php/phpdoctor/annotationParser.js'

      - name: Add Annotations
        uses: pmagentur/linting-annotations@v0.1
        if: failure() && steps.linter.outputs.annotations != ''
        with:
          commitSha: ${{ github.event.pull_request.head.sha }}
          checkName: 'PHP Linting'
          annotations: ${{ steps.linter.outputs.annotations }}
