name: Pull Request checks

on:
  workflow_call:
    inputs:
      configs-path:
        description: 'Set this to override the linting configs with the ones in this folder. 
        The structure inside of the folder must be the same as the one in this repository.'
        required: false
        type: string
        default: '._linting' # Use the configs from this repository (separate checkout)
      excluded-directories:
        description: 'List of directories to exclude (JSON), empty = none'
        required: false
        type: string
        default: '[]'

jobs:
  linting:
    runs-on: ubuntu-latest
    name: phpmd & phpDoctor
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files from caller repository
        id: changedFiles
        uses: tj-actions/changed-files@v34
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}

      # Needed to have access to the linter files
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          repository: pmagentur/linting-php
          path: ._linting

      - name: Linting with phpmd
        id: linterPhpmd
        uses: pmagentur/linting-action@v0.4
        with:
          changed-files: ${{ steps.changedFiles.outputs.all_changed_files }}
          linter-command: "php ._linting/phpmd/phpmd.phar {files} checkstyle ${{ inputs.configs-path }}/phpmd/config.xml"
          file-separator: ','
          relevant-file-endings: '["php"]'
          parser-type: 'xml'
          annotation-parser: '._linting/phpmd/annotationParser.js'
          excluded-directories: ${{ inputs.excluded-directories }}

      - name: Linting with phpDoctor
        if: success() || failure()
        id: linterPhpDoctor
        uses: pmagentur/linting-action@v0.4
        with:
          changed-files: ${{ steps.changedFiles.outputs.all_changed_files }}
          linter-command: "php ._linting/phpdoctor/phpdoctor.phar analyse {files}"
          relevant-file-endings: '["php"]'
          parser-type: 'custom'
          annotation-parser: '._linting/phpdoctor/annotationParser.js'
          annotations: ${{ steps.linterPhpmd.outputs.annotations }}
          excluded-directories: ${{ inputs.excluded-directories }}

      - name: Add Annotations
        uses: pmagentur/linting-annotations@v0.1
        if: failure() && steps.linterPhpDoctor.outputs.annotations != ''
        with:
          commitSha: ${{ github.event.pull_request.head.sha }}
          checkName: 'PHP Linting'
          annotations: ${{ steps.linterPhpDoctor.outputs.annotations }}
